DROP TABLE IF EXISTS images;

CREATE TABLE images(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(256) NOT NULL,
    file VARCHAR(256) NOT NULL
);